### ISSUE TITLE
Send logs to Log Aggregator

### ISSUE THREAD

**Issue by deepbrook** [raiden-network/raiden-service-bundle#44]
Since our kibana server is now online, please update the docker-compose files to forward logs to 
the fluentd port:

```yaml
    logging:
      driver: fluentd
      options:
        fluentd-address: logs.raiden.network:24224
        tag: raiden.transport.<instance_number>.<docker-service>
```

An example configuration for the traefik container running in the pod on transport02 would thus be:

```yaml
services:
  traefik:
    ...
    logging:
      driver: fluentd
      options:
        fluentd-address: logs.raiden.network:24224
        tag: raiden.transport.02.traefik
```

Please note that the url is only available from within the VPN. Otherwise an IP address is required as the address.
